apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    editable: false
    jsonData:
      tracesToMetricsV2:
        datasourceUid: prometheus
        queries:
          - name: Request rate
            query: rate(kafka_messages_consumed_total{$$__tags}[5m])
