apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-service
  namespace: fixflux
  labels:
    app: market-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-data-service
  template:
    metadata:
      labels:
        app: market-data-service
    spec:
      containers:
        - name: market-data-service
          image: market-data-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: fixflux-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
