name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: |
          pip install -r requirements.txt
          pip install -e .
      - name: Run unit tests with coverage
        env:
          LOG_LEVEL: DEBUG
          LOG_FORMAT: json
        run: |
          pytest tests/test_price.py \
            --cov=calculator \
            --cov-report=term \
            --cov-report=xml \
            --cov-fail-under=90 \
            --log-cli-level=DEBUG

  bdd-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: |
          pip install -r requirements.txt
          pip install -e .
      - name: Run BDD tests with HTML report & logs
        env:
          LOG_LEVEL: INFO
          LOG_FORMAT: json
        run: |
          pytest tests/test_price_bdd.py \
            --html=report.html \
            --self-contained-html \
            --log-cli-level=INFO | tee logs.txt
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: bdd-report
          path: report.html
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: logs.txt
