---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: redpanda
    {{ include "fixflux.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: kafka
      port: 9092
    - name: rpc
      port: 33145
  selector:
    app: redpanda
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: {{ .Values.namespace }}
  labels:
    app: redpanda
    {{ include "fixflux.labels" . | nindent 4 }}
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: admin
      port: 9644
      targetPort: 9644
  selector:
    app: redpanda
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redpanda.storage }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: {{ .Values.namespace }}
  labels:
    app: redpanda
    {{ include "fixflux.labels" . | nindent 4 }}
spec:
  serviceName: redpanda-headless
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: {{ .Values.redpanda.image }}
          command:
            - redpanda
            - start
            - --smp=1
            - --memory=1G
            - --overprovisioned
            - --kafka-addr=0.0.0.0:9092
            - --advertise-kafka-addr=redpanda:9092
            - --pandaproxy-addr=0.0.0.0:8082
            - --advertise-pandaproxy-addr=redpanda:8082
            - --rpc-addr=0.0.0.0:33145
            - --advertise-rpc-addr=redpanda-0.redpanda-headless.{{ .Values.namespace }}.svc.cluster.local:33145
            - --mode=dev-container
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9644
              name: admin
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: redpanda-data
              mountPath: /var/lib/redpanda/data
          resources:
            {{- toYaml .Values.redpanda.resources | nindent 12 }}
      volumes:
        - name: redpanda-data
          persistentVolumeClaim:
            claimName: redpanda-data
