apiVersion: v1
kind: Secret
metadata:
  name: fixflux-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "fixflux.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.postgres.credentials.user | quote }}
  postgres-password: {{ .Values.postgres.credentials.password | quote }}
  postgres-db: {{ .Values.postgres.credentials.database | quote }}
  database-url: {{ include "fixflux.databaseUrl" . | quote }}
